CREATE DATABASE employee_tracker;
USE employee_tracker;


CREATE TABLE department (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (30) NOT NULL
);

CREATE TABLE role (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR (30) NOT NULL,
    salary DECIMAL,
    department_id INT
);

CREATE TABLE employee (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR (30) NOT NULL,
    last_name VARCHAR(30) NOT NULL
    role_id INT NOT NULL
    manager_id INT NULL
);

--MAKE SURE TO JOIN THESE TABLES USING FOREIGN KEY. LOOK AT ACTIVITY 20 FOR A GUIDE